apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
spec:
  selector:
    matchLabels:
      app: weather-app
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-app
        env: development
    spec:
      containers:
      - name: weather-app
        image: gcr.io/secure-current-313023/weather-app:v1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: weather-app
